/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.MidiaControl;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author marip
 */
public class FTelaCadastroMidia extends javax.swing.JFrame {
    
    private MidiaControl mic;
    /**
     * Creates new form FTelaCadrastroLivro
     */
    public FTelaCadastroMidia(MidiaControl mic) {
        this.mic = mic;
        mic.setTcmi(this);
        initComponents();
        mic.carregarMidias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTituloPrincipal = new javax.swing.JLabel();
        pBotoes = new javax.swing.JPanel();
        bntOk = new javax.swing.JToggleButton();
        bntCancelar = new javax.swing.JToggleButton();
        pDados = new javax.swing.JPanel();
        lTituloItem = new javax.swing.JLabel();
        lAutores = new javax.swing.JLabel();
        lAno = new javax.swing.JLabel();
        lCidade = new javax.swing.JLabel();
        lEditora = new javax.swing.JLabel();
        lEdicao = new javax.swing.JLabel();
        lCdu = new javax.swing.JLabel();
        lAssunto = new javax.swing.JLabel();
        lPalavra1 = new javax.swing.JLabel();
        lPalavra2 = new javax.swing.JLabel();
        lTamanho = new javax.swing.JLabel();
        lQuantidade = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        tfAutores = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfEdicao = new javax.swing.JTextField();
        tfEditora = new javax.swing.JTextField();
        tfPalavra2 = new javax.swing.JTextField();
        tfPalavra1 = new javax.swing.JTextField();
        tfAssunto = new javax.swing.JTextField();
        tfTamanho = new javax.swing.JTextField();
        TfQuantidade = new javax.swing.JTextField();
        ftfAno = new javax.swing.JFormattedTextField();
        ftfCdu = new javax.swing.JFormattedTextField();
        lid = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        lEmprestimo = new javax.swing.JLabel();
        tfEmprestimo = new javax.swing.JTextField();
        lTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        pTabela = new javax.swing.JPanel();
        bntAlterar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JToggleButton();
        spTabelaMidia = new javax.swing.JScrollPane();
        tMidias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Mídias");

        lTituloPrincipal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 24)); // NOI18N
        lTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTituloPrincipal.setText("Cadastro de Mídia");
        lTituloPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bntOk.setText("Ok");
        bntOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOkActionPerformed(evt);
            }
        });

        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotoesLayout = new javax.swing.GroupLayout(pBotoes);
        pBotoes.setLayout(pBotoesLayout);
        pBotoesLayout.setHorizontalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntOk)
                .addGap(18, 18, 18)
                .addComponent(bntCancelar)
                .addGap(47, 47, 47))
        );
        pBotoesLayout.setVerticalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntOk)
                    .addComponent(bntCancelar))
                .addGap(15, 15, 15))
        );

        pDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lTituloItem.setText("Título: ");

        lAutores.setText("Autores: ");

        lAno.setText("Ano:");

        lCidade.setText("Cidade:");

        lEditora.setText("Editora");
        lEditora.setToolTipText("");

        lEdicao.setText("Edição:");

        lCdu.setText("CDU:");

        lAssunto.setText("Assunto:");

        lPalavra1.setText("Palavra chave 1:");

        lPalavra2.setText("Palavra chave 2:");

        lTamanho.setText("Tamanho:");

        lQuantidade.setText("Quantidade:");

        try {
            ftfAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfCdu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##:###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lid.setText("ID:");

        lEmprestimo.setText("Empréstimo:");

        lTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fita VHS", "DVD", "CD" }));

        javax.swing.GroupLayout pDadosLayout = new javax.swing.GroupLayout(pDados);
        pDados.setLayout(pDadosLayout);
        pDadosLayout.setHorizontalGroup(
            pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDadosLayout.createSequentialGroup()
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTituloItem)
                            .addComponent(lCidade)
                            .addComponent(lEditora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(lTamanho))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pDadosLayout.createSequentialGroup()
                                        .addComponent(lQuantidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosLayout.createSequentialGroup()
                                        .addComponent(lEdicao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(lid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(lAutores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(pDadosLayout.createSequentialGroup()
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pDadosLayout.createSequentialGroup()
                                        .addComponent(lAssunto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(lPalavra1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPalavra1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lPalavra2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPalavra2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(lCdu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfCdu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lEmprestimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pDadosLayout.setVerticalGroup(
            pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTituloItem)
                    .addComponent(lAutores)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCidade)
                    .addComponent(lAno)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEdicao)
                    .addComponent(tfEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lid)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEditora)
                    .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTamanho)
                    .addComponent(tfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lQuantidade)
                    .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAssunto)
                    .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPalavra1)
                    .addComponent(tfPalavra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPalavra2)
                    .addComponent(tfPalavra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCdu)
                    .addComponent(ftfCdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmprestimo)
                    .addComponent(tfEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        tMidias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Quantidade", "Empréstimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTabelaMidia.setViewportView(tMidias);

        javax.swing.GroupLayout pTabelaLayout = new javax.swing.GroupLayout(pTabela);
        pTabela.setLayout(pTabelaLayout);
        pTabelaLayout.setHorizontalGroup(
            pTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTabelaLayout.createSequentialGroup()
                .addContainerGap(655, Short.MAX_VALUE)
                .addComponent(bntAlterar)
                .addGap(18, 18, 18)
                .addComponent(bntExcluir)
                .addGap(47, 47, 47))
            .addComponent(spTabelaMidia, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        pTabelaLayout.setVerticalGroup(
            pTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelaMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAlterar)
                    .addComponent(bntExcluir))
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(pTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lTituloPrincipal)
                .addGap(47, 47, 47)
                .addComponent(pDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pDados.getAccessibleContext().setAccessibleName("Dados");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOkActionPerformed
        // TODO add your handling code here:
        mic.cadastrarMidia();
    }//GEN-LAST:event_bntOkActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
        mic.excluirMidia();
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        // TODO add your handling code here:
        mic.alterarMidia();  //Carregar os dados para alterar
        mic.excluirMidia();
    }//GEN-LAST:event_bntAlterarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfQuantidade;
    private javax.swing.JButton bntAlterar;
    private javax.swing.JToggleButton bntCancelar;
    private javax.swing.JToggleButton bntExcluir;
    private javax.swing.JToggleButton bntOk;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JFormattedTextField ftfAno;
    private javax.swing.JFormattedTextField ftfCdu;
    private javax.swing.JLabel lAno;
    private javax.swing.JLabel lAssunto;
    private javax.swing.JLabel lAutores;
    private javax.swing.JLabel lCdu;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lEdicao;
    private javax.swing.JLabel lEditora;
    private javax.swing.JLabel lEmprestimo;
    private javax.swing.JLabel lPalavra1;
    private javax.swing.JLabel lPalavra2;
    private javax.swing.JLabel lQuantidade;
    private javax.swing.JLabel lTamanho;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lTituloItem;
    private javax.swing.JLabel lTituloPrincipal;
    private javax.swing.JLabel lid;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pDados;
    private javax.swing.JPanel pTabela;
    private javax.swing.JScrollPane spTabelaMidia;
    private javax.swing.JTable tMidias;
    private javax.swing.JTextField tfAssunto;
    private javax.swing.JTextField tfAutores;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEdicao;
    private javax.swing.JTextField tfEditora;
    private javax.swing.JTextField tfEmprestimo;
    private javax.swing.JTextField tfPalavra1;
    private javax.swing.JTextField tfPalavra2;
    private javax.swing.JTextField tfTamanho;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfid;
    // End of variables declaration//GEN-END:variables

    public JTextField getTfQuantidade() {
        return TfQuantidade;
    }

    public JButton getBntAlterar() {
        return bntAlterar;
    }

    public JToggleButton getBntCancelar() {
        return bntCancelar;
    }

    public JToggleButton getBntExcluir() {
        return bntExcluir;
    }

    public JToggleButton getBntOk() {
        return bntOk;
    }

    public JComboBox<String> getCbTipo() {
        return cbTipo;
    }

    public JFormattedTextField getFtfAno() {
        return ftfAno;
    }

    public JFormattedTextField getFtfCdu() {
        return ftfCdu;
    }

    public JLabel getlAno() {
        return lAno;
    }

    public JLabel getlAssunto() {
        return lAssunto;
    }

    public JLabel getlAutores() {
        return lAutores;
    }

    public JLabel getlCdu() {
        return lCdu;
    }

    public JLabel getlCidade() {
        return lCidade;
    }

    public JLabel getlEdicao() {
        return lEdicao;
    }

    public JLabel getlEditora() {
        return lEditora;
    }

    public JLabel getlEmprestimo() {
        return lEmprestimo;
    }

    public JLabel getlPalavra1() {
        return lPalavra1;
    }

    public JLabel getlPalavra2() {
        return lPalavra2;
    }

    public JLabel getlQuantidade() {
        return lQuantidade;
    }

    public JLabel getlTamanho() {
        return lTamanho;
    }

    public JLabel getlTipo() {
        return lTipo;
    }

    public JLabel getlTituloItem() {
        return lTituloItem;
    }

    public JLabel getlTituloPrincipal() {
        return lTituloPrincipal;
    }

    public JLabel getLid() {
        return lid;
    }

    public JPanel getpBotoes() {
        return pBotoes;
    }

    public JPanel getpDados() {
        return pDados;
    }

    public JPanel getpTabela() {
        return pTabela;
    }

    public JScrollPane getSpTabelaMidia() {
        return spTabelaMidia;
    }

    public JTable gettMidias() {
        return tMidias;
    }

    public JTextField getTfAssunto() {
        return tfAssunto;
    }

    public JTextField getTfAutores() {
        return tfAutores;
    }

    public JTextField getTfCidade() {
        return tfCidade;
    }

    public JTextField getTfEdicao() {
        return tfEdicao;
    }

    public JTextField getTfEditora() {
        return tfEditora;
    }

    public JTextField getTfEmprestimo() {
        return tfEmprestimo;
    }

    public JTextField getTfPalavra1() {
        return tfPalavra1;
    }

    public JTextField getTfPalavra2() {
        return tfPalavra2;
    }

    public JTextField getTfTamanho() {
        return tfTamanho;
    }

    public JTextField getTfTitulo() {
        return tfTitulo;
    }

    public JTextField getTfid() {
        return tfid;
    }

    

}
