/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.LivroControl;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author marip
 */
public class FTelaCadastroLivro extends javax.swing.JFrame {
    
    private LivroControl lc;
    /**
     * Creates new form FTelaCadrastroLivro
     */
    public FTelaCadastroLivro(LivroControl lc) {
        this.lc = lc;
        lc.setTcl(this);
        initComponents();
        lc.carregarLivros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTituloPrincipal = new javax.swing.JLabel();
        pBotoes = new javax.swing.JPanel();
        bntOk = new javax.swing.JToggleButton();
        bntCancelar = new javax.swing.JToggleButton();
        pDados = new javax.swing.JPanel();
        lTituloItem = new javax.swing.JLabel();
        lAutores = new javax.swing.JLabel();
        lAno = new javax.swing.JLabel();
        lCidade = new javax.swing.JLabel();
        lEditora = new javax.swing.JLabel();
        lEdicao = new javax.swing.JLabel();
        lCdu = new javax.swing.JLabel();
        lAssunto = new javax.swing.JLabel();
        lPalavra1 = new javax.swing.JLabel();
        lPalavra2 = new javax.swing.JLabel();
        lTamanho = new javax.swing.JLabel();
        lQuantidade = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        tfAutores = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfEdicao = new javax.swing.JTextField();
        tfEditora = new javax.swing.JTextField();
        tfPalavra2 = new javax.swing.JTextField();
        tfPalavra1 = new javax.swing.JTextField();
        tfAssunto = new javax.swing.JTextField();
        tfTamanho = new javax.swing.JTextField();
        TfQuantidade = new javax.swing.JTextField();
        ftfAno = new javax.swing.JFormattedTextField();
        ftfCdu = new javax.swing.JFormattedTextField();
        lisbn = new javax.swing.JLabel();
        ftfisbn = new javax.swing.JFormattedTextField();
        lPaginas = new javax.swing.JLabel();
        tfPaginas = new javax.swing.JTextField();
        lid = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        lEmprestimo = new javax.swing.JLabel();
        tfEmprestimo = new javax.swing.JTextField();
        pTabela = new javax.swing.JPanel();
        bntAlterar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JToggleButton();
        spTabelaLivro = new javax.swing.JScrollPane();
        tLivros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Livros");

        lTituloPrincipal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 24)); // NOI18N
        lTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTituloPrincipal.setText("Cadastro de livro");
        lTituloPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bntOk.setText("Ok");
        bntOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOkActionPerformed(evt);
            }
        });

        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotoesLayout = new javax.swing.GroupLayout(pBotoes);
        pBotoes.setLayout(pBotoesLayout);
        pBotoesLayout.setHorizontalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntOk)
                .addGap(18, 18, 18)
                .addComponent(bntCancelar)
                .addGap(47, 47, 47))
        );
        pBotoesLayout.setVerticalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntOk)
                    .addComponent(bntCancelar))
                .addGap(15, 15, 15))
        );

        pDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lTituloItem.setText("Título: ");

        lAutores.setText("Autores: ");

        lAno.setText("Ano:");

        lCidade.setText("Cidade:");

        lEditora.setText("Editora");
        lEditora.setToolTipText("");

        lEdicao.setText("Edição:");

        lCdu.setText("CDU:");

        lAssunto.setText("Assunto:");

        lPalavra1.setText("Palavra chave 1:");

        lPalavra2.setText("Palavra chave 2:");

        lTamanho.setText("Tamanho:");

        lQuantidade.setText("Quantidade:");

        try {
            ftfAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfCdu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##:###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lisbn.setText("ISBN:");

        try {
            ftfisbn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-###-####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lPaginas.setText("Páginas:");

        lid.setText("ID:");

        lEmprestimo.setText("Empréstimo:");

        javax.swing.GroupLayout pDadosLayout = new javax.swing.GroupLayout(pDados);
        pDados.setLayout(pDadosLayout);
        pDadosLayout.setHorizontalGroup(
            pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDadosLayout.createSequentialGroup()
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pDadosLayout.createSequentialGroup()
                                        .addComponent(lAssunto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(lPalavra1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPalavra1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(lisbn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lCdu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfCdu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lEmprestimo))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lPalavra2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(tfEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(tfPalavra2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pDadosLayout.createSequentialGroup()
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTituloItem)
                            .addComponent(lCidade)
                            .addComponent(lEditora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(lTamanho))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pDadosLayout.createSequentialGroup()
                                        .addComponent(lQuantidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDadosLayout.createSequentialGroup()
                                        .addComponent(lEdicao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pDadosLayout.createSequentialGroup()
                                        .addComponent(lPaginas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pDadosLayout.createSequentialGroup()
                                        .addComponent(lid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pDadosLayout.createSequentialGroup()
                                .addComponent(lAutores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        pDadosLayout.setVerticalGroup(
            pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTituloItem)
                    .addComponent(lAutores)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCidade)
                    .addComponent(lAno)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEdicao)
                    .addComponent(tfEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPaginas)
                    .addComponent(tfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEditora)
                    .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTamanho)
                    .addComponent(tfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lQuantidade)
                    .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lid)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAssunto)
                    .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPalavra1)
                    .addComponent(tfPalavra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPalavra2)
                    .addComponent(tfPalavra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lisbn)
                    .addComponent(ftfisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCdu)
                    .addComponent(ftfCdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmprestimo)
                    .addComponent(tfEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        tLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Quantidade", "Empréstimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTabelaLivro.setViewportView(tLivros);

        javax.swing.GroupLayout pTabelaLayout = new javax.swing.GroupLayout(pTabela);
        pTabela.setLayout(pTabelaLayout);
        pTabelaLayout.setHorizontalGroup(
            pTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTabelaLayout.createSequentialGroup()
                .addContainerGap(655, Short.MAX_VALUE)
                .addComponent(bntAlterar)
                .addGap(18, 18, 18)
                .addComponent(bntExcluir)
                .addGap(47, 47, 47))
            .addComponent(spTabelaLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        pTabelaLayout.setVerticalGroup(
            pTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAlterar)
                    .addComponent(bntExcluir))
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(pTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lTituloPrincipal)
                .addGap(47, 47, 47)
                .addComponent(pDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pDados.getAccessibleContext().setAccessibleName("Dados");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOkActionPerformed
        // TODO add your handling code here:
        lc.cadastrarLivro();
    }//GEN-LAST:event_bntOkActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
        lc.excluirLivro();
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        // TODO add your handling code here:
        lc.alterarLivro();  //Carregar os dados para alterar
        lc.excluirLivro();
    }//GEN-LAST:event_bntAlterarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfQuantidade;
    private javax.swing.JButton bntAlterar;
    private javax.swing.JToggleButton bntCancelar;
    private javax.swing.JToggleButton bntExcluir;
    private javax.swing.JToggleButton bntOk;
    private javax.swing.JFormattedTextField ftfAno;
    private javax.swing.JFormattedTextField ftfCdu;
    private javax.swing.JFormattedTextField ftfisbn;
    private javax.swing.JLabel lAno;
    private javax.swing.JLabel lAssunto;
    private javax.swing.JLabel lAutores;
    private javax.swing.JLabel lCdu;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lEdicao;
    private javax.swing.JLabel lEditora;
    private javax.swing.JLabel lEmprestimo;
    private javax.swing.JLabel lPaginas;
    private javax.swing.JLabel lPalavra1;
    private javax.swing.JLabel lPalavra2;
    private javax.swing.JLabel lQuantidade;
    private javax.swing.JLabel lTamanho;
    private javax.swing.JLabel lTituloItem;
    private javax.swing.JLabel lTituloPrincipal;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lisbn;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pDados;
    private javax.swing.JPanel pTabela;
    private javax.swing.JScrollPane spTabelaLivro;
    private javax.swing.JTable tLivros;
    private javax.swing.JTextField tfAssunto;
    private javax.swing.JTextField tfAutores;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEdicao;
    private javax.swing.JTextField tfEditora;
    private javax.swing.JTextField tfEmprestimo;
    private javax.swing.JTextField tfPaginas;
    private javax.swing.JTextField tfPalavra1;
    private javax.swing.JTextField tfPalavra2;
    private javax.swing.JTextField tfTamanho;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfid;
    // End of variables declaration//GEN-END:variables

    public JTextField getTfQuantidade() {
        return TfQuantidade;
    }

    public JButton getBntAlterar() {
        return bntAlterar;
    }

    public JToggleButton getBntCancelar() {
        return bntCancelar;
    }

    public JToggleButton getBntExcluir() {
        return bntExcluir;
    }

    public JToggleButton getBntOk() {
        return bntOk;
    }

    public JFormattedTextField getFtfAno() {
        return ftfAno;
    }

    public JFormattedTextField getFtfCdu() {
        return ftfCdu;
    }

    public JFormattedTextField getFtfisbn() {
        return ftfisbn;
    }

    public JLabel getlAno() {
        return lAno;
    }

    public JLabel getlAssunto() {
        return lAssunto;
    }

    public JLabel getlAutores() {
        return lAutores;
    }

    public JLabel getlCdu() {
        return lCdu;
    }

    public JLabel getlCidade() {
        return lCidade;
    }

    public JLabel getlEdicao() {
        return lEdicao;
    }

    public JLabel getlEditora() {
        return lEditora;
    }

    public JLabel getlEmprestimo() {
        return lEmprestimo;
    }

    public JLabel getlPaginas() {
        return lPaginas;
    }

    public JLabel getlPalavra1() {
        return lPalavra1;
    }

    public JLabel getlPalavra2() {
        return lPalavra2;
    }

    public JLabel getlQuantidade() {
        return lQuantidade;
    }

    public JLabel getlTamanho() {
        return lTamanho;
    }

    public JLabel getlTituloItem() {
        return lTituloItem;
    }

    public JLabel getlTituloPrincipal() {
        return lTituloPrincipal;
    }

    public JLabel getLid() {
        return lid;
    }

    public JLabel getLisbn() {
        return lisbn;
    }

    public JPanel getpBotoes() {
        return pBotoes;
    }

    public JPanel getpDados() {
        return pDados;
    }

    public JPanel getpTabela() {
        return pTabela;
    }

    public JScrollPane getSpTabelaLivro() {
        return spTabelaLivro;
    }

    public JTable gettLivros() {
        return tLivros;
    }

    public JTextField getTfAssunto() {
        return tfAssunto;
    }

    public JTextField getTfAutores() {
        return tfAutores;
    }

    public JTextField getTfCidade() {
        return tfCidade;
    }

    public JTextField getTfEdicao() {
        return tfEdicao;
    }

    public JTextField getTfEditora() {
        return tfEditora;
    }

    public JTextField getTfEmprestimo() {
        return tfEmprestimo;
    }

    public JTextField getTfPaginas() {
        return tfPaginas;
    }

    public JTextField getTfPalavra1() {
        return tfPalavra1;
    }

    public JTextField getTfPalavra2() {
        return tfPalavra2;
    }

    public JTextField getTfTamanho() {
        return tfTamanho;
    }

    public JTextField getTfTitulo() {
        return tfTitulo;
    }

    public JTextField getTfid() {
        return tfid;
    }

    public void setTfQuantidade(JTextField TfQuantidade) {
        this.TfQuantidade = TfQuantidade;
    }

    public void setBntAlterar(JButton bntAlterar) {
        this.bntAlterar = bntAlterar;
    }

    public void setBntCancelar(JToggleButton bntCancelar) {
        this.bntCancelar = bntCancelar;
    }

    public void setBntExcluir(JToggleButton bntExcluir) {
        this.bntExcluir = bntExcluir;
    }

    public void setBntOk(JToggleButton bntOk) {
        this.bntOk = bntOk;
    }

    public void setFtfAno(JFormattedTextField ftfAno) {
        this.ftfAno = ftfAno;
    }

    public void setFtfCdu(JFormattedTextField ftfCdu) {
        this.ftfCdu = ftfCdu;
    }

    public void setFtfisbn(JFormattedTextField ftfisbn) {
        this.ftfisbn = ftfisbn;
    }

    public void setlAno(JLabel lAno) {
        this.lAno = lAno;
    }

    public void setlAssunto(JLabel lAssunto) {
        this.lAssunto = lAssunto;
    }

    public void setlAutores(JLabel lAutores) {
        this.lAutores = lAutores;
    }

    public void setlCdu(JLabel lCdu) {
        this.lCdu = lCdu;
    }

    public void setlCidade(JLabel lCidade) {
        this.lCidade = lCidade;
    }

    public void setlEdicao(JLabel lEdicao) {
        this.lEdicao = lEdicao;
    }

    public void setlEditora(JLabel lEditora) {
        this.lEditora = lEditora;
    }

    public void setlEmprestimo(JLabel lEmprestimo) {
        this.lEmprestimo = lEmprestimo;
    }

    public void setlPaginas(JLabel lPaginas) {
        this.lPaginas = lPaginas;
    }

    public void setlPalavra1(JLabel lPalavra1) {
        this.lPalavra1 = lPalavra1;
    }

    public void setlPalavra2(JLabel lPalavra2) {
        this.lPalavra2 = lPalavra2;
    }

    public void setlQuantidade(JLabel lQuantidade) {
        this.lQuantidade = lQuantidade;
    }

    public void setlTamanho(JLabel lTamanho) {
        this.lTamanho = lTamanho;
    }

    public void setlTituloItem(JLabel lTituloItem) {
        this.lTituloItem = lTituloItem;
    }

    public void setlTituloPrincipal(JLabel lTituloPrincipal) {
        this.lTituloPrincipal = lTituloPrincipal;
    }

    public void setLid(JLabel lid) {
        this.lid = lid;
    }

    public void setLisbn(JLabel lisbn) {
        this.lisbn = lisbn;
    }

    public void setpBotoes(JPanel pBotoes) {
        this.pBotoes = pBotoes;
    }

    public void setpDados(JPanel pDados) {
        this.pDados = pDados;
    }

    public void setpTabela(JPanel pTabela) {
        this.pTabela = pTabela;
    }

    public void setSpTabelaLivro(JScrollPane spTabelaLivro) {
        this.spTabelaLivro = spTabelaLivro;
    }

    public void settLivros(JTable tLivros) {
        this.tLivros = tLivros;
    }

    public void setTfAssunto(JTextField tfAssunto) {
        this.tfAssunto = tfAssunto;
    }

    public void setTfAutores(JTextField tfAutores) {
        this.tfAutores = tfAutores;
    }

    public void setTfCidade(JTextField tfCidade) {
        this.tfCidade = tfCidade;
    }

    public void setTfEdicao(JTextField tfEdicao) {
        this.tfEdicao = tfEdicao;
    }

    public void setTfEditora(JTextField tfEditora) {
        this.tfEditora = tfEditora;
    }

    public void setTfEmprestimo(JTextField tfEmprestimo) {
        this.tfEmprestimo = tfEmprestimo;
    }

    public void setTfPaginas(JTextField tfPaginas) {
        this.tfPaginas = tfPaginas;
    }

    public void setTfPalavra1(JTextField tfPalavra1) {
        this.tfPalavra1 = tfPalavra1;
    }

    public void setTfPalavra2(JTextField tfPalavra2) {
        this.tfPalavra2 = tfPalavra2;
    }

    public void setTfTamanho(JTextField tfTamanho) {
        this.tfTamanho = tfTamanho;
    }

    public void setTfTitulo(JTextField tfTitulo) {
        this.tfTitulo = tfTitulo;
    }

    public void setTfid(JTextField tfid) {
        this.tfid = tfid;
    }

    
}
