/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.CartazControl;
import control.ItensGeraisControl;
import control.LivroControl;
import control.MapaControl;
import control.MidiaControl;
import control.PeriodicoControl;
import control.RelatorioControl;
import control.TCCControl;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
/**
 *
 * @author marip
 */
public class FTelaPrincipal extends javax.swing.JFrame {
    
    LivroControl lc;
    RelatorioControl rc;
    MapaControl mc;
    CartazControl cc;
    PeriodicoControl pc;
    TCCControl tc;
    MidiaControl mic;
    ItensGeraisControl ed;
    ItensGeraisControl pi;
    /**
     * Creates new form FTelaPrincipal
     */
    public FTelaPrincipal() {
        lc = new LivroControl();
        rc = new RelatorioControl();
        mc = new MapaControl();
        cc = new CartazControl();
        pc = new PeriodicoControl();
        tc = new TCCControl();
        mic = new MidiaControl();
        ed = new ItensGeraisControl();
        pi = new ItensGeraisControl();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbTelePrincipal = new javax.swing.JMenuBar();
        mLogin = new javax.swing.JMenu();
        miLogin = new javax.swing.JCheckBoxMenuItem();
        miSair = new javax.swing.JCheckBoxMenuItem();
        mManterAcervo = new javax.swing.JMenu();
        miCartaz = new javax.swing.JCheckBoxMenuItem();
        miLivro = new javax.swing.JCheckBoxMenuItem();
        miMapa = new javax.swing.JCheckBoxMenuItem();
        miMidia = new javax.swing.JCheckBoxMenuItem();
        miPeriodico = new javax.swing.JCheckBoxMenuItem();
        miRelatorio = new javax.swing.JCheckBoxMenuItem();
        miTCC = new javax.swing.JCheckBoxMenuItem();
        mFuncoes = new javax.swing.JMenu();
        miEmprestarDevolver = new javax.swing.JCheckBoxMenuItem();
        miPesquisar = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acervo da biblioteca");

        mLogin.setText("Login");

        miLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miLogin.setText("Login");
        miLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoginActionPerformed(evt);
            }
        });
        mLogin.add(miLogin);

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mLogin.add(miSair);

        mbTelePrincipal.add(mLogin);

        mManterAcervo.setText("Manter Acervo");
        mManterAcervo.setEnabled(false);

        miCartaz.setText("Cartaz");
        miCartaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCartazActionPerformed(evt);
            }
        });
        mManterAcervo.add(miCartaz);

        miLivro.setText("Livro");
        miLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLivroActionPerformed(evt);
            }
        });
        mManterAcervo.add(miLivro);

        miMapa.setText("Mapa");
        miMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMapaActionPerformed(evt);
            }
        });
        mManterAcervo.add(miMapa);

        miMidia.setText("Mídia");
        miMidia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMidiaActionPerformed(evt);
            }
        });
        mManterAcervo.add(miMidia);

        miPeriodico.setText("Periódico");
        miPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPeriodicoActionPerformed(evt);
            }
        });
        mManterAcervo.add(miPeriodico);

        miRelatorio.setText("Relatório");
        miRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioActionPerformed(evt);
            }
        });
        mManterAcervo.add(miRelatorio);

        miTCC.setText("TCC");
        miTCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTCCActionPerformed(evt);
            }
        });
        mManterAcervo.add(miTCC);

        mbTelePrincipal.add(mManterAcervo);

        mFuncoes.setText("Funções");

        miEmprestarDevolver.setText("Emprestar/Devolver");
        miEmprestarDevolver.setActionCommand("");
        miEmprestarDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmprestarDevolverActionPerformed(evt);
            }
        });
        mFuncoes.add(miEmprestarDevolver);

        miPesquisar.setText("Pesquisar item");
        miPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPesquisarActionPerformed(evt);
            }
        });
        mFuncoes.add(miPesquisar);

        mbTelePrincipal.add(mFuncoes);

        setJMenuBar(mbTelePrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
        // Botão para login
        DTelaLogin telaLogin = new DTelaLogin(this, true);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_miLoginActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // Botão Para sair do sistema
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair do sistema?", "Sair", JOptionPane.OK_OPTION);
        System.out.println(op);
        
        if(op == 0)
            dispose();
    }//GEN-LAST:event_miSairActionPerformed

    private void miLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLivroActionPerformed
        // TODO add your handling code here:
        FTelaCadastroLivro telaLivro = new FTelaCadastroLivro(lc);
        telaLivro.setVisible(true);
    }//GEN-LAST:event_miLivroActionPerformed

    private void miRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioActionPerformed
        // TODO add your handling code here:
        FTelaCadastroRelatorio telaRelatorio = new FTelaCadastroRelatorio(rc);
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_miRelatorioActionPerformed

    private void miMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMapaActionPerformed
        // TODO add your handling code here:
        FTelaCadastroMapa telaMapa = new FTelaCadastroMapa(mc);
        telaMapa.setVisible(true);
    }//GEN-LAST:event_miMapaActionPerformed

    private void miCartazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCartazActionPerformed
        // TODO add your handling code here:
        FTelaCadastroCartaz telaCartaz = new FTelaCadastroCartaz(cc);
        telaCartaz.setVisible(true);
    }//GEN-LAST:event_miCartazActionPerformed

    private void miPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPeriodicoActionPerformed
        // TODO add your handling code here:
        FTelaCadastroPeriodico telaPeriodico = new FTelaCadastroPeriodico(pc);
        telaPeriodico.setVisible(true);
    }//GEN-LAST:event_miPeriodicoActionPerformed

    private void miTCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTCCActionPerformed
        // TODO add your handling code here:
        FTelaCadastroTCC telaTCC = new FTelaCadastroTCC(tc);
        telaTCC.setVisible(true);
    }//GEN-LAST:event_miTCCActionPerformed

    private void miMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMidiaActionPerformed
        // TODO add your handling code here:
        FTelaCadastroMidia telaMidia = new FTelaCadastroMidia(mic);
        telaMidia.setVisible(true);
    }//GEN-LAST:event_miMidiaActionPerformed

    private void miEmprestarDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmprestarDevolverActionPerformed
        // TODO add your handling code here:
        FTelaEmprestimoDevolucao telaED = new FTelaEmprestimoDevolucao(ed);
        telaED.setVisible(true);
    }//GEN-LAST:event_miEmprestarDevolverActionPerformed

    private void miPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPesquisarActionPerformed
        // TODO add your handling code here:
        FTelaPesquisaItem telaPI = new FTelaPesquisaItem(pi);
        telaPI.setVisible(true);
    }//GEN-LAST:event_miPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mFuncoes;
    private javax.swing.JMenu mLogin;
    private javax.swing.JMenu mManterAcervo;
    private javax.swing.JMenuBar mbTelePrincipal;
    private javax.swing.JCheckBoxMenuItem miCartaz;
    private javax.swing.JCheckBoxMenuItem miEmprestarDevolver;
    private javax.swing.JCheckBoxMenuItem miLivro;
    private javax.swing.JCheckBoxMenuItem miLogin;
    private javax.swing.JCheckBoxMenuItem miMapa;
    private javax.swing.JCheckBoxMenuItem miMidia;
    private javax.swing.JCheckBoxMenuItem miPeriodico;
    private javax.swing.JCheckBoxMenuItem miPesquisar;
    private javax.swing.JCheckBoxMenuItem miRelatorio;
    private javax.swing.JCheckBoxMenuItem miSair;
    private javax.swing.JCheckBoxMenuItem miTCC;
    // End of variables declaration//GEN-END:variables

    public JMenu getmFuncoes() {
        return mFuncoes;
    }

    public JMenu getmLogin() {
        return mLogin;
    }

    public JMenu getmManterAcervo() {
        return mManterAcervo;
    }

    public JMenuBar getMbTelePrincipal() {
        return mbTelePrincipal;
    }

    public JCheckBoxMenuItem getMiCartaz() {
        return miCartaz;
    }

    public JMenuItem getMiEmprestarDevolver() {
        return miEmprestarDevolver;
    }

    public JCheckBoxMenuItem getMiLivro() {
        return miLivro;
    }

    public JCheckBoxMenuItem getMiLogin() {
        return miLogin;
    }

    public JCheckBoxMenuItem getMiMapa() {
        return miMapa;
    }

    public JCheckBoxMenuItem getMiMidia() {
        return miMidia;
    }

    public JCheckBoxMenuItem getMiPeriodico() {
        return miPeriodico;
    }

    public JCheckBoxMenuItem getMiRelatorio() {
        return miRelatorio;
    }

    public JCheckBoxMenuItem getMiSair() {
        return miSair;
    }

    public JCheckBoxMenuItem getMiTCC() {
        return miTCC;
    }

    
    
    
    
}
